---
title: Batterijen gebruiken met de micro:bit
hero_image: images/banner.png
description: Batterijen gebruiken met de micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: 'Batterijen gebruiken met de micro:bit'

