title: Utiliser les piles avec le micro:bit
hero_image: images/banner.png
description: Utilise des piles avec le micro:bit
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: 'Utiliser les piles avec le micro:bit'

